run:from flask import Flask, request, jsonify
import re

app = Flask(__name__)

def is_strong_password(password):
    # Password must be at least 8 characters long, contain at least one uppercase letter,
    # one lowercase letter, one digit, and one special character.
    if len(password) < 8:
        return False
    if not re.search(r'[A-Z]', password):
        return False
    if not re.search(r'[a-z]', password):
        return False
    if not re.search(r'[0-9]', password):
        return False
    if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
        return False
    return True

@app.route('/signup', methods=['POST'])
def signup():
    data = request.get_json()
    
    # Extract username and password
    username = data.get('username')
    password = data.get('password')
    
    # Check if username and password are provided
    if not username or not password:
        return jsonify({"error": "Username and password are required"}), 400
    
    # Validate password strength
    if not is_strong_password(password):
        return jsonify({"error": "Password is not strong enough"}), 400
    
    # Proceed with user registration (e.g., save to database)
    # For this example, we'll just return a success message.
    return jsonify({"message": "User registered successfully"}), 201

if __name__ == '__main__':
    app.run(debug=True)
